name: vora
description: "An Exclusive Shopping App."
version: 1.0.0+1
environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  intl: 0.20.2
  dio: ^5.3.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/languages/
  # fonts:
  #   - family: Segoe UI
  #     fonts:
  #       - asset: assets/fonts/SegoeUI-Regular.ttf
  #       - asset: assets/fonts/SegoeUI-Bold.ttf
  #         weight: 700
